# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - name: Checkout Branch
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    #- name: Npm run bulid and install
    - run: npm install
    - run: npm run build
    
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.1.2
      with:
        SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
        REMOTE_HOST: 118.25.0.64
        REMOTE_USER: ubuntu
        SOURCE: dist
        # TARGET: # optional, default is /home/REMOTE_USER/
