# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: pwd
    - run: npm ci
    - run: npm run build --if-present

    
    #- name: ssh deploy
     # uses: easingthemes/ssh-deploy@v2.1.2
      #with:
       # SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
        #REMOTE_HOST: 118.25.0.64
        #REMOTE_USER: ubuntu
        #SOURCE: dist
        # TARGET: # optional, default is /home/REMOTE_USER/
